version: "3"
services:
  db:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    env_file: backend/.prod.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  web:
    build: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: backend/.prod.env
    depends_on:
      - db
