version: "3"

tasks:
  run:
    cmds:
      - docker run --net host ghcr.io/Samir984/near_book

  build:
    cmds:
      - docker build . -t ghcr.io/Samir984/near_book

  publish:
    cmds:
      - docker image push ghcr.io/Samir984/near_book
