# Generated by Django 5.2 on 2025-05-05 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_book_core_book_publica_efdc9d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('LIKE NEW', 'Like New'), ('GOOD', 'Good'), ('MODERATE', 'Moderate'), ('POOR', 'Poor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
