# Generated by Django 5.2 on 2025-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_condition_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
