# Generated by Django 5.2 on 2025-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_book_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
