# Generated by Django 5.2 on 2025-05-08 06:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_latitude_alter_book_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
