# Generated by Django 5.2 on 2025-05-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkitem',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bookmark'),
        ),
    ]
