# Generated by Django 5.2 on 2025-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bookmarkitem_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
