# Generated by Django 5.2 on 2025-05-30 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_book_rating_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Bookmark'},
        ),
        migrations.AlterModelOptions(
            name='bookmarkitem',
            options={'verbose_name': 'BookMark Item'},
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
